name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install project dependencies
      run: cd cryptoquestmmorpg-dapp && npm install --legacy-peer-deps

    - name: Install Tailwind and PostCSS dependencies
      run: cd cryptoquestmmorpg-dapp && npm install -D tailwindcss postcss autoprefixer --legacy-peer-deps

    - name: Install blockchain dependencies
      run: cd cryptoquestmmorpg-dapp && npm install web3 ethers@5 @metamask/detect-provider @uniswap/sdk @ethersproject/address @ethersproject/abi @ethersproject/providers @ethersproject/contracts --legacy-peer-deps

    - name: Initialize Tailwind CSS
      run: cd cryptoquestmmorpg-dapp && npx tailwindcss init -p

    - name: Check for requirements.txt
      id: check_req_file
      run: |
        if [ -f "cryptoquestmmorpg-dapp/src/data-processing-and-analytics/requirements.txt" ]; then
          echo "requirements.txtBased on the information found, the error `ERR_PACKAGE_PATH_NOT_EXPORTED` is due to a breaking change in `ethers` version 6. It seems the most reliable solution is to downgrade to `ethers` version 5, which is more stable and widely supported by other libraries.
