name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Create React App and Install Dependencies
      run: make create-react-app install-dependencies install-blockchain-dependencies

    - name: Check for requirements.txt
      id: check_req_file
      run: |
        if [ -f "cryptoquestmmorpg-dapp/src/data-processing-and-analytics/requirements.txt" ]; then
          echo "requirements.txt file found."
          echo "::set-output name=req_exists::true"
        else
          echo "requirements.txt file not found."
          echo "::set-output name=req_exists::false"
        fi

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
      if: steps.check_req_file.outputs.req_exists == 'true'

    - name: Set up Python environment
      run: make setup-python-env
      if: steps.check_req_file.outputs.req_exists == 'true'

    - name: Build project
      run: make build

    - name: Test project
      run: make test

    - name: Format code
      run: make format

    - name: Clean project
      run: make clean

    - name: Clean Python environment
      run: make clean-python-env
      if: steps.check_req_file.outputs.req_exists == 'true'
