name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install project dependencies
      run: cd cryptoquestmmorpg-dapp && npm install --legacy-peer-deps

    - name: Install Tailwind and PostCSS dependencies
      run: cd cryptoquestmmorpg-dapp && npm install -D tailwindcss postcss autoprefixer --legacy-peer-deps

    - name: Install blockchain dependencies
      run: cd cryptoquestmmorpg-dapp && npm install web3 ethers @metamask/detect-provider --legacy-peer-deps

    - name: Initialize Tailwind CSS
      run: cd cryptoquestmmorpg-dapp && npx tailwindcss init -p

    - name: Check for requirements.txt
      id: check_req_file
      run: |
        if [ -f "cryptoquestmmorpg-dapp/src/data-processing-and-analytics/requirements.txt" ]; then
          echo "requirements.txt file found."
          echo "::set-output name=req_exists::true"
        else
          echo "requirements.txt file not found."
          echo "::set-output name=req_exists::false"
        fi

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
      if: steps.check_req_file.outputs.req_exists == 'true'

    - name: Set up Python environment
      run: |
        python3 -m venv env
        env/bin/pip install -r cryptoquestmmorpg-dapp/src/data-processing-and-analytics/requirements.txt
      if: steps.check_req_file.outputs.req_exists == 'true'

    - name: Build arbitrage bot
      run: cd cryptoquestmmorpg-dapp && npm run build-bot

    - name: Run arbitrage bot
      run: cd cryptoquestmmorpg-dapp && npm run run-bot

    - name: Build project
      run: cd cryptoquestmmorpg-dapp && npm run build

    - name: Test project
      run: cd cryptoquestmmorpg-dapp && npm test

    - name: Format code
      run: cd cryptoquestmmorpg-dapp && npm run format

    - name: Eject project configuration (optional)
      run: cd cryptoquestmmorpg-dapp && npm run eject

    - name: Clean project
      run: make clean

    - name: Clean Python environment
      run: make clean-python-env
      if: steps.check_req_file.outputs.req_exists == 'true'
