name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install project dependencies
      run: cd cryptoquestmmorpg-dapp && npm install

    - name: Install Tailwind and PostCSS dependencies
      run: cd cryptoquestmmorpg-dapp && npm install -D tailwindcss postcss autoprefixer

    - name: Install blockchain dependencies
      run: cd cryptoquestmmorpg-dapp && npm install web3 ethers

    - name: Initialize Tailwind CSS
      run: cd cryptoquestmmorpg-dapp && npx tailwindcss init -p

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Set up Python environment
      run: |
        python3 -m venv env
        env/bin/pip install -r requirements.txt

    - name: Build arbitrage bot
      run: cd cryptoquestmmorpg-dapp && node src/build-arbitrage-bot.js

    - name: Run arbitrage bot
      run: cd cryptoquestmmorpg-dapp && node src/arbitrage-bot.js

    - name: Build project
      run: cd cryptoquestmmorpg-dapp && npm run build

    - name: Test project
      run: cd cryptoquestmmorpg-dapp && npm test

    - name: Format code
      run: cd cryptoquestmmorpg-dapp && npm run format

    - name: Eject project configuration (optional)
      run: cd cryptoquestmmorpg-dapp && npm run eject

    - name: Clean project
      run: make clean

    - name: Clean Python environment
      run: make clean-python-env
