name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Node.js dependencies
      run: |
        cd cryptoquestmmorpg-dapp
        npm install --legacy-peer-deps

    - name: Install blockchain dependencies
      run: |
        cd cryptoquestmmorpg-dapp
        npm install web3 ethers @uniswap/sdk @aave/contract-helpers reflect-metadata dotenv --legacy-peer-deps

    - name: Setup Python environment
      run: |
        python3 -m venv env
        source env/bin/activate
        pip install -r cryptoquestmmorpg-dapp/src/data-processing-and-analytics/requirements.txt

    - name: Build the app
      run: |
        cd cryptoquestmmorpg-dapp
        npm run build

    - name: Test the app
      run: |
        cd cryptoquestmmorpg-dapp
        npm run test

    - name: Run the bot
      run: |
        cd cryptoquestmmorpg-dapp
        node src/arbitrage-bot.js
