name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version

    - name: Install Python dependencies
      run: |
        python3 -m venv env
        source env/bin/activate
        pip install -r cryptoquestmmorpg-dapp/src/data-processing-and-analytics/requirements.txt

    - name: Install Node.js dependencies
      run: make install-dependencies

    - name: Install blockchain dependencies
      run: make install-blockchain-dependencies

    - name: Run tests
      run: make test

    - name: Build project
      run: make build

    - name: Start application
      run: make start

    - name: Build bot
      run: make build-bot

    - name: Run bot
      run: make run-bot
