name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build arbitrage bot
      run: npm run build-bot

    - name: Run arbitrage bot
      run: npm run run-bot

    - name: Setup Python environment
      run: |
        python3 -m venv env
        source env/bin/activate
        pip install -r src/data-processing-and-analytics/requirements.txt

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
