name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make install-dependencies

    - name: Run tests
      run: make test

    - name: Build project
      run: make build

    - name: Lint project
      run: make lint

    - name: Format project
      run: make format
