name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install Dependencies
        run: make install-dependencies install-blockchain-dependencies

      # Setup Python environment
      - name: Setup Python Environment
        run: make setup-python-env

      # Run Build
      - name: Build Project
        run: make build

      # Run Tests
      - name: Run Tests
        run: make test

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies for linting
      - name: Install Linting Dependencies
        run: make install-dependencies

      # Run Lint
      - name: Lint Code
        run: make ci-lint

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-and-test # Ensures the build-and-test job passes first

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Deploy the build
      - name: Deploy to Server
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          rsync -avz --delete $(APP_NAME)/build ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}
